version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=${ENV:-development}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lawyers_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
    depends_on:
      - db
    networks:
      - lexic-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lawyers_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lexic-network

networks:
  lexic-network:
    driver: bridge

volumes:
  postgres_data: